CREATE schema bildverwaltung;
CREATE TABLE bildverwaltung.ALBUM (ID VARCHAR(36) NOT NULL, COMMENT LONGVARCHAR, CREATIONDATE TIMESTAMP NOT NULL, LASTUPDATE TIMESTAMP NOT NULL, NAME VARCHAR NOT NULL UNIQUE, PRIMARY KEY (ID));
CREATE TABLE bildverwaltung.PICTURE (ID VARCHAR(36) NOT NULL, COMMENT LONGVARCHAR, CREATIONDATE TIMESTAMP NOT NULL, EXTENSION VARCHAR NOT NULL, HEIGTH INTEGER NOT NULL, LASTUPDATE TIMESTAMP NOT NULL, NAME VARCHAR NOT NULL, URI VARCHAR NOT NULL, WIDTH INTEGER NOT NULL, PRIMARY KEY (ID), RATING SMALLINT NOT NULL);
CREATE TABLE bildverwaltung.RESOURCESTRING (TRANSLATION VARCHAR NOT NULL, COUNTRYKEY VARCHAR NOT NULL, RESOURCESTRINGID VARCHAR NOT NULL, LANGUAGEKEY VARCHAR NOT NULL, PRIMARY KEY (COUNTRYKEY, RESOURCESTRINGID, LANGUAGEKEY));
CREATE TABLE bildverwaltung.ALBUM_PICTURE (alben_ID VARCHAR(36) NOT NULL, pictures_ID VARCHAR(36) NOT NULL, PRIMARY KEY (alben_ID, pictures_ID));
ALTER TABLE bildverwaltung.ALBUM_PICTURE ADD CONSTRAINT FK_ALBUM_PICTURE_alben_ID FOREIGN KEY (alben_ID) REFERENCES bildverwaltung.ALBUM (ID);
ALTER TABLE bildverwaltung.ALBUM_PICTURE ADD CONSTRAINT FK_ALBUM_PICTURE_pictures_ID FOREIGN KEY (pictures_ID) REFERENCES bildverwaltung.PICTURE (ID);
ALTER TABLE bildverwaltung.PICTURE ADD CONSTRAINT RATING_RANGE CHECK(RATING >= 0 AND RATING <= 5);
